name: esheba_fixian
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  firebase_messaging: ^16.1.0

  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.2.2
  firebase_app_check: ^0.4.1+2
  http: ^1.2.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  geolocator: 14.0.2
  geocoding: ^4.0.0
  flutter_typeahead: ^5.0.0
  url_launcher: ^6.2.5
  cloudinary_api: ^1.1.1
  cloudinary_url_gen: ^1.8.0
  image_cropper: ^11.0.0
  image_picker: ^1.2.1
  camera: ^0.11.3
  image: ^4.7.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
